---
title: "CodeBook"
author: "Daniel Romero"
output: html_document
---

**Data set: Smartphone-Based Recognition of Human Activities and Postural Transitions Data Set** 

**Feature Selection** 

The features selected for this database come from the accelerometer and gyroscope 3-axial raw signals TimeDomain.Accelerometer-XYZ and TimeDomain.Gyroscope-XYZ. These time domain signals (prefix 'TimeDomain' to denote time) were captured at a constant rate of 50 Hz. Then they were filtered using a median filter and a 3rd order low pass Butterworth filter with a corner frequency of 20 Hz to remove noise. Similarly, the acceleration signal was then separated into body and gravity acceleration signals (TimeDomain.Body.Accelerometer-XYZ and TimeDomain.GravityAccelerometer-XYZ) using another low pass Butterworth filter with a corner frequency of 0.3 Hz. 

Subsequently, the body linear acceleration and angular velocity were derived in time to obtain Jerk signals (TimeDomain.BodyAccelerometer.Jerk-XYZ and TimeDomain.BodyGyroscope.Jerk-XYZ). 

The Fast Fourier Transform (FFT) was applied to some of these signals producing FrequencyDomain.BodyAccelerometer-XYZ, FrequencyDomain.BodyAccelerometer.Jerk-XYZ, FrequencyDomain.BodyGyroscope-XYZ, FrequencyDomain.BodyAccelerometer.JerkMagnitude, FrequencyDomain.BodyGyroscope.Magnitude, FrequencyDomain.BodyGyroscope.JerkMagnitude. (Note the 'FrequencyDomain' to indicate frequency domain signals). 

These signals were used to estimate variables of the feature vector for each pattern:  
'-XYZ' is used to denote 3-axial signals in the X, Y and Z directions.

- TimeDomain.BodyAccelerometer-XYZ

- TimeDomain.GravityAccelerometer-XYZ

- TimeDomain.BodyAccelerometer.Jerk-XYZ

- TimeDomain.BodyGyroscope-XYZ

- TimeDomain.BodyGyroscope.Jerk-XYZ

- TimeDomain.BodyAccelerometer.Magnitude

- TimeDomain.GravityAccelerometer.Magnitude

- TimeDomain.BodyAccelerometer.JerkMagnitude

- TimeDomain.BodyGyroscope.Magnitude

- TimeDomain.BodyGyroscope.JerkMagnitude

- FrequencyDomain.BodyAccelerometer-XYZ

- FrequencyDomain.BodyAccelerometer.Jerk-XYZ

- FrequencyDomain.BodyGyroscope-XYZ

- FrequencyDomain.BodyAccelerometer.Magnitue

- FrequencyDomain.BodyAccelerometer.JerkMagnitude

- FrequencyDomain.BodyGyroscope.Magnitude

- FrequencyDomain.BodyGyroscope.JerkMagnitude


**The set of variables that were estimated from these signals are:** 

1. Mean: Mean value

2. SD: Standard deviation

Finally, the average of each variable for each activity and subject was obtained.


The complete list of variables of each feature vector is available in **'FeaturesNames.txt'**


